### ISSUE TITLE
Feature: Add Navbar And Footer to The Website

### ISSUE THREAD

**Issue by shreyash3087** [subinoybiswas/clippy#19]
**Description:**
I would like to suggest adding a navigation bar (navbar) and a footer to enhance the user experience and improve navigation on the Clippy platform. I have already designed these components and am willing to implement them.

**Proposed Changes:**

**Navbar:**

- A responsive navigation bar that includes links to key sections such as Home, Abouts, and Contact.
- A logo positioned at the left side.
- A hamburger menu for mobile devices

**Footer:**

- A footer that contains the logo,and the copryright message.
- Designed to be simple and consistent with the overall aesthetic of the site.

**Design:**

I have attached the designs below:
![Screenshot (2)](https://github.com/subinoybiswas/clippy/assets/72603662/9d0a1f56-1b5d-4d49-bd42-320db8f0e764)
![Screenshot (1)](https://github.com/subinoybiswas/clippy/assets/72603662/dde0a9f6-1310-4d90-960e-284161d2b49a)
![Screenshot (3)](https://github.com/subinoybiswas/clippy/assets/72603662/cfcb3df4-04bd-4bc0-be1a-55c945296ea0)

**Benefits:**

- Improved user navigation and accessibility.
- Enhanced look and feel of the website.
- More professional and complete user interface.

**Implementation Plan:**

- Create reusable components for the navbar and footer.
- Integrate these components into the existing layout.
- Ensure responsiveness and cross-browser compatibility.

**Additional Context:**
I am happy to contribute by implementing these features myself. Please let me know if you have any feedback or additional requirements.

**[X] I am a GSSOC'24 Contributor**

Thank you for considering my request!

**Comment by subinoybiswas** [comment]
No need for a hamburger menu, you can add a footer but make it very subtle, the text should be small, and the background should be transparent, you can use icons there, also add a button for the about-us page

**Comment by shreyash3087** [comment]
@subinoybiswas I added the Hamburger menu considering the future sections that might be added in the site,the hamburger would make sure that the links (Home,Github,Abouts) do not overflow over each other and are visible in small screens/mobile devices. although right now since the webpage features a single section(i.e Home),i agree that it would be better to not include hamburger,it would look something like this if we dont include the hamburger-

![screencapture-localhost-3000-2024-06-01-16_06_51](https://github.com/subinoybiswas/clippy/assets/72603662/32cd1988-e2b3-4121-87cb-7f60479a99f2)
![screencapture-localhost-3000-2024-06-01-16_06_39](https://github.com/subinoybiswas/clippy/assets/72603662/c5b33845-24bb-4a35-8c25-8046093d9d20)


**Since we dont have a logo yet,i decided to make a temporary logo for now**,also as far as the footer goes,making it transparent makes it look a bit off,and it doesnt match with the color scheme,so i believe having it like this serves its purpose as it looks minimilistic and clean,if you still want the footer to be transparent,i can do that as per your requirements.

Please confirm if you want to go with this design or if you want the hamburger design.

Thankyou

**Comment by shreyash3087** [comment]
@subinoybiswas I am sorry,i think i didnt completely understand your suggestion,do you want me to not put a navbar at all or do you not just want the hamburger menu,if you dont want the hamburger menu,i can do that and the design would look something like this-

![screencapture-localhost-3000-2024-06-01-16_06_51](https://github.com/subinoybiswas/clippy/assets/72603662/373cc6f5-9f1a-4481-930f-762d40c1aa82)
![screencapture-localhost-3000-2024-06-01-16_06_39](https://github.com/subinoybiswas/clippy/assets/72603662/71481773-43ca-44d4-98ad-fac13624c5a1)

**(Made a temporary logo since we dont have one for now)**
Note: The Hamburger menu was added so that the links(Home,Abouts,Github) dont overflow each other,but in this case it doesn't since we dont have many sections in the webapp

If you dont want the navbar at all and for the footer you want it to be transparent-

![screencapture-localhost-3000-2024-06-01-16_52_48](https://github.com/subinoybiswas/clippy/assets/72603662/6afc3ae0-f235-4697-ae58-5f90ad46a520)


Please Do Confirm Your Requirements

ThankYou

**Comment by subinoybiswas** [comment]
The second choice, I don't want navigation menus at all, 
![image](https://github.com/subinoybiswas/clippy/assets/115915591/9584714c-efc6-4264-94ef-9d401cf253fb)

Make the GitHub and AboutUs a logo and don't start with the Copyright logo keep it in the middle
