### ISSUE TITLE
[FEAT]: Adding an error message for non-existent clippy id 

### ISSUE THREAD

**Issue by aryansharma220** [subinoybiswas/clippy#20]
We can add an error message if user tries to enter an invalid/ wrong clippy ID.

Please assign it to me under gssoc24 if you would like me to work on it.

**Comment by subinoybiswas** [comment]
Assigned! use toast messages to show this.

**Comment by aryansharma220** [comment]
@subinoybiswas Ok so I can make a request to the database to check weather the entered id exists or not, if it doesn't exist do you want me to show error or redirect to this page?
