### ISSUE TITLE
Creating  a 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [subinoybiswas/clippy#22]
it redirect to the 404 not found error page but show this || Please check the video

https://github.com/subinoybiswas/clippy/assets/125277258/10eddb97-1270-4e8e-aeb4-2de55b0bd9b1

**Comment by subinoybiswas** [comment]
Sure you can implement a 404 page, if you want me to assign you please reply indicating the same

**Comment by subinoybiswas** [comment]
This feature is already asked for in a previous issue [Issue #20 ](https://github.com/subinoybiswas/clippy/issues/20)

**Comment by RamakrushnaBiswal** [comment]
@subinoybiswas i can make the 404 not found page but issue #20  solve the problem why it occures

**Comment by subinoybiswas** [comment]
Okay go ahead
