### ISSUE TITLE
Cliipy page UI enhancement

### ISSUE THREAD

**Issue by Rohitha-pudu** [subinoybiswas/clippy#29]
The current one is cool,but if we can modify a little it would be great
i will work on this issue ,please assign this to me

**Comment by subinoybiswas** [comment]
Make a Design first, highlighting what changes you want to make

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/subinoybiswas/clippy/assets/116823590/fb6f0265-fd0f-4fdf-bca6-05926bd71b65)

**Comment by subinoybiswas** [comment]
The existing design looks better in my opinion, closing this issue.

You can contribute in other ways. Contributions are always welcome.
