### ISSUE TITLE
[Feature Request]:  We can add review button in right bottom 

### ISSUE THREAD

**Issue by dhruv8433** [subinoybiswas/clippy#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@subinoybiswas 

check this out 
we can add one message button in right side bottom

### Use Case

when user click on that one pop up open and it take message

### Benefits

it help user to measure overall rating and reviews

### Add ScreenShots

![image](https://github.com/subinoybiswas/clippy/assets/114583978/16b4475c-def2-4e08-ba46-d56620dc1e7f)

we can add somethign like this

![image](https://github.com/subinoybiswas/clippy/assets/114583978/462262c5-8fd1-4a55-a69f-d36a8aa8ac06)

and on that button click, this kind of popup open

![image](https://github.com/subinoybiswas/clippy/assets/114583978/310b29d6-9cbf-4c6d-aee0-05f611c3f57e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure you can add a review section, but add the button to the left side as right side is already occupied.

Also follow these instructions-

1. Make a Modal popup when button is clicked.
2. Make sure the theming and styling is consistent
3. Use NextUI for the Modals, Input etc
4. The review should send an email to my email account(You can test with your own)
5. Use loops/emailjs as a email service.(You can test using your account, keep it documented and I can create my own service later)

**Comment by dhruv8433** [comment]
Please assign it to me

**Comment by subinoybiswas** [comment]
Assigned
