### ISSUE TITLE
[Documentation Update]: Wanted to add contributors section in Readme.md file

### ISSUE THREAD

**Issue by mukund-gpt** [subinoybiswas/clippy#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

 **List of Contributors in Readme.md file missing**

### Suggested Change

**add contributors section in Readme.md file**

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure you can add a contributors section.

But confirm if it would be dynamic and won't need any manual changes afterwards

**Comment by mukund-gpt** [comment]
### Contributors list can updated by just simply update the Readme.md manually
 
### OR
![Screenshot 2024-06-04 160159](https://github.com/subinoybiswas/clippy/assets/142800930/d4aebb49-470d-4eb7-8035-db657f314bb5)

**github Action may be better option, but contributors can't do this, only authors have permissions**

**Comment by mukund-gpt** [comment]
### i recommend,  simply update the Readme.md manually whenever required
