### ISSUE TITLE
[Feature Request]: Footer for the website 

### ISSUE THREAD

**Issue by Amruta7203** [subinoybiswas/clippy#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose having a dedicated footer for the website for better user experience.

### Use Case

The footer for a website is the main component where the users reach out for any queries 

### Benefits

Better User experience 
Enhanced UI

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
The design of clippy is made minimal for ease of use, and if something doesn't contribute to the simplicity, it isn't there.

You can give a png or screenshot with the changes you are proposing, if it goes well with the design and theme, you can go ahead with it

**Comment by Amruta7203** [comment]
@subinoybiswas I have made changes in the footer to make it more aligned and clearly visible :
![image](https://github.com/subinoybiswas/clippy/assets/116087736/7a7041d5-8eb0-481c-88f6-9b28ee1a40c6)

Pls confirm if this okay..

**Comment by subinoybiswas** [comment]
I updated the footer recently, mention if something can be improved or you can close this issue

**Comment by Amruta7203** [comment]
@subinoybiswas There is a duplicate functionality for closing the message input which is not required and any one can be eliminated. (the cross icon or the close button)

![image](https://github.com/subinoybiswas/clippy/assets/116087736/c8f278d2-67a3-4fb0-8e98-d9a6ab5efacf)

**Comment by subinoybiswas** [comment]
You can create a separate issue for this
