### ISSUE TITLE
[Feature Request]: scroll not complementing the theme of the website 

### ISSUE THREAD

**Issue by Amruta7203** [subinoybiswas/clippy#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current scroll bar is not aligning to the theme of the website. It needs to be redesigned

### Use Case

Better UI and visual appeal

### Benefits

Better UI and visual appeal

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure you can go ahead with this issue, but before making a PR please give a screenshot here, so I can confirm

**Comment by Amruta7203** [comment]
@subinoybiswas This is the custom scroll bar with aesthetic color complementing the color palette of the website.
![image](https://github.com/subinoybiswas/clippy/assets/116087736/5c3b1a9e-feb7-4722-b3a9-fdab4c85ceaa)

should i raise a PR for the same?

**Comment by subinoybiswas** [comment]
sure, also the white bg of the outer scrollbar is not looking great either, do something about that as well
