### ISSUE TITLE
[Feature Request]:  Adding a validation for content field 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [subinoybiswas/clippy#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When i left the field empty and generate clippy so that clippy id was generated but actually i didn't entered any data or not uploaded any file .

### Use Case

This will help to remove unwanted empty clippies .

### Add ScreenShots

https://github.com/subinoybiswas/clippy/assets/118350936/d35090dc-8c7f-475f-bac7-24ffba6e8ac4

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure, go ahead with it, you can use toasts to convey that the message is empty, or you can use something else too, but make sure it goes with the theme, and don't use `alert()` it doesn't look that good.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
