### ISSUE TITLE
[Feature Request]: Add .env.example file

### ISSUE THREAD

**Issue by dhairyathedev** [subinoybiswas/clippy#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add .env.example file

### Use Case

Including a `.env.example` file provides new contributors with a clear reference for the MongoDB secrets the application uses and how the code interacts with environment variables.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure, you can add the .env.example

Use this for reference
![335879220-771fe2da-1f23-4bee-a7df-bc7272482679](https://github.com/subinoybiswas/clippy/assets/115915591/7b7566a4-f31c-4808-9205-84578f5f6fc0)
