### ISSUE TITLE
[Feature Request]: No clip id  without any data submit

### ISSUE THREAD

**Issue by Khushalsarode** [subinoybiswas/clippy#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- when we create an clip id when by adding text data its also work for empty field when clicked create its gives id to access empty clip
- adding an .env file to project with empty value so user can add values of his own
- also need to update the .env part in documentation
### Use Case

- its flood an database with empty unwanted data fields
- its useless and program run for no data

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Already Merged, in previous pull request https://github.com/subinoybiswas/clippy/pull/43
