### ISSUE TITLE
[Feature Request]: Create two components side by side for "get" and "create"

### ISSUE THREAD

**Issue by Khushalsarode** [subinoybiswas/clippy#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- when we get text the component gets expanded, and we have empty area on screen so we will create this create and get components side by side to each other.
- as they are now vertically stacked want to make it horizontally
- enhancement in style of error message 

### Use Case

![Screenshot 2024-06-05 163759](https://github.com/subinoybiswas/clippy/assets/105520366/311c7ec1-de1e-4ba5-81af-936277cd5521)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
I am not quite understanding the changes you want, please explain it a bit further, you can use pen tool on the screenshot to explain what you want to change

**Comment by subinoybiswas** [comment]
Yes

**Comment by Khushalsarode** [comment]
![Screenshot 2024-06-07 022535](https://github.com/subinoybiswas/clippy/assets/105520366/b4972ece-d8e1-4c41-92ac-a8dd834c77d7)

- adjust components
- adjust the footer

**Comment by Khushalsarode** [comment]
> Yes

so? I should or not?

**Comment by subinoybiswas** [comment]
No, the existing is more straightforward
