### ISSUE TITLE
[Bug]: There is a duplicate functionality for closing the message input which is not required 

### ISSUE THREAD

**Issue by Amruta7203** [subinoybiswas/clippy#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@subinoybiswas There is a duplicate functionality for closing the message input which is not required and any one can be eliminated. (the cross icon or the close button)

### Expected behavior

any one close option can be eliminated 

### Add ScreenShots

![image](https://github.com/subinoybiswas/clippy/assets/116087736/3e0cb5e5-c959-4a07-97e8-1a84db29c6e2)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure go ahead and fix it
