### ISSUE TITLE
adding a back button icon to the back button element

### ISSUE THREAD

**Issue by 05hiteshbansal** [subinoybiswas/clippy#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A header will be added to the top to make website more appealing to the users

### Use Case

A header will be added to the top to make website more appealing to the users

### Add ScreenShots

![image](https://github.com/subinoybiswas/clippy/assets/83907989/0813423e-4620-4a92-84ad-49543316f357)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
I think header goes against the simplicity of the design, so no headers

**Comment by subinoybiswas** [comment]
Merging the Back Button Changes and changing Issue title for better clarity

**Comment by subinoybiswas** [comment]
Duplicate Issue closing this
