### ISSUE TITLE
[Documentation Update]: Add License

### ISSUE THREAD

**Issue by Priyanshu2631** [subinoybiswas/clippy#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

MIT License is missing in this repository, I want to add it, please assign me the issue under GSSOC'24.

### Suggested Change

Attach MIT License into the repository in the PR.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
okay go ahead
