### ISSUE TITLE
[Feature Request]: Access Error Notification for Invalid Clippy ID

### ISSUE THREAD

**Issue by satmm** [subinoybiswas/clippy#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementing an error notification feature for Clippy that alerts users when they attempt to access clipboard content using an invalid Clippy ID. This feature will enhance user experience by providing immediate feedback on errors, guiding users to correct their actions without confusion or frustration.

### Use Case

When a user attempts to retrieve clipboard content by entering a Clippy ID that does not exist or is incorrectly typed, the system should display an error notification on the screen. This notification will inform the user that the Clippy ID they entered is invalid, prompting them to check and re-enter the correct ID. This feature helps prevent wasted time and frustration by providing clear and immediate feedback on access errors.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
There is an pull closed request regarding this, you can use that as your reference, go ahead with it.
https://github.com/subinoybiswas/clippy/pull/25

**Comment by satmm** [comment]
![Screenshot (250)](https://github.com/subinoybiswas/clippy/assets/81502695/82c0025c-0044-4e2d-bb90-6e6ee3c49859)


I am getting this error when ever i am trying to create a Clippy any idea where i am going wrong or how to fix ?? @subinoybiswas

**Comment by subinoybiswas** [comment]
Maybe for some reason data in undefined, not sure.

**Comment by 05hiteshbansal** [comment]
@subinoybiswas  I contributed in one of issue in this project and i encounterd similar error . I think I can resolve this issue can you also assign me this issue .

**Comment by satmm** [comment]
@subinoybiswas  I have sent you pull request, Please review the changes and let me know if any adjustments are needed. #69

**Comment by sanjay-kv** [comment]
@subinoybiswas Im the Program manager of gssoc, could you please add me into  your repo. need to work on the label issues reported by other contributors.

**Comment by subinoybiswas** [comment]
> @subinoybiswas Im the Program manager of gssoc, could you please add me into your repo. need to work on the label issues reported by other contributors.

added
