### ISSUE TITLE
[Feature Request]:  Closed Issue Greeting

### ISSUE THREAD

**Issue by thevijayshankersharma** [subinoybiswas/clippy#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The feature entails implementing a standardized greeting message for closing issues within the project's issue tracker. This greeting will serve as a closing remark whenever an issue is marked as resolved or closed. The message should be succinct, polite, and informative, conveying gratitude to the contributor for their effort while also providing any necessary next steps or additional information.

### Use Case

This feature would streamline communication within the project's issue tracker by ensuring consistency and professionalism in closing interactions. Currently, there might be variations in how issues are closed, leading to potential confusion or inconsistency in the project's communication standards. With a standardized greeting, contributors and maintainers alike can expect a clear and courteous closing message for every resolved issue.

### Benefits

Improved User Experience: Contributors will appreciate the clear communication and acknowledgment of their contributions, fostering a positive environment within the project.
Enhanced Project Organization: Consistent closing messages will contribute to better organization within the issue tracker, making it easier for contributors to navigate and understand the status of various issues.
Community Engagement: By maintaining professionalism and gratitude in closing interactions, the project can foster stronger community engagement and encourage continued contributions from contributors.
Time Efficiency: Having a predefined closing greeting saves time for maintainers by eliminating the need to craft individual messages for each closed issue, allowing them to focus more on active development and issue resolution.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
sure go ahead
