### ISSUE TITLE
[Feature Request]: Add a Feedback Form with Popup on Button Click

### ISSUE THREAD

**Issue by MastanSayyad** [subinoybiswas/clippy#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance user interaction and gather valuable feedback, I suggest adding a feedback form to the "Clippy" website. The form should appear as a popup when a dedicated button is clicked. This will allow users to provide their opinions, report issues, and suggest improvements seamlessly.

### Use Case

- User: Clicks on the "Give Feedback" button.
- System: Displays the feedback form as a popup.
- User: Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- User: Clicks the "Submit" button on the form.
- System: Displays a confirmation message indicating the feedback was submitted successfully.
- User: Closes the feedback form popup.

### Benefits

- User Engagement
- Improvement Opportunities.
- Issue Reporting.
- Customer Satisfaction

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
It's already there, https://github.com/subinoybiswas/clippy/issues/35
