### ISSUE TITLE
[Feature Request]: add social media icons 

### ISSUE THREAD

**Issue by jayanththalla** [subinoybiswas/clippy#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is only one social media icon so adding social media they share easily through the social media 

### Use Case

It will useful to share the things

### Add ScreenShots

![image](https://github.com/subinoybiswas/clippy/assets/121346142/53e75975-e6f8-48ba-aa9b-23df06dd80ed)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Adding more icons would make it very convoluted, however you can add the icons in the about page if you want(in the footer)
