### ISSUE TITLE
[Feature Request]: Adding custom cursor

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [subinoybiswas/clippy#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding  custom cursor

### Use Case

https://tholman.com/cursor-effects/

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
assign it to me under GSSOC

**Comment by subinoybiswas** [comment]
I think a custom cursor would make it very convoluted.

**Comment by RamakrushnaBiswal** [comment]
@subinoybiswas i think it looks good

**Comment by subinoybiswas** [comment]
fork this, and try it on your end, if it looks good and as per the theme I might merge it, but I am not promising anything.

**Comment by RamakrushnaBiswal** [comment]
solved #76
