### ISSUE TITLE
[Feature Request]: Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [subinoybiswas/clippy#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@subinoybiswas I want to add a Login/Signup Page to the website.Kindly assign this issue to me.

### Use Case

NA

### Benefits

NA

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
There is no login page by design, so there is no hindrance to copy and paste
