### ISSUE TITLE
[Bug]: No Cursor in slug page

### ISSUE THREAD

**Issue by kom-senapati** [subinoybiswas/clippy#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I write clippy id and press get it redirects to another page and cursor is not there. And in about us also its normal cursor.

### Expected behavior

Cursor should be available at all pages

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure you can fix it, if you want

**Comment by kom-senapati** [comment]
@subinoybiswas You can check pr
