### ISSUE TITLE
[Bug]: Missing about page and scrollbar issue

### ISSUE THREAD

**Issue by kom-senapati** [subinoybiswas/clippy#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No about us button in main page and scrollbar in the about us page.

### Expected behavior

A button should be added in main page to redirect to about us page, and height should be of screen to remove scrollbar

### Add ScreenShots

![image](https://github.com/subinoybiswas/clippy/assets/92045934/f588919a-bb3a-4073-a55e-e91306c706f2)

![image](https://github.com/subinoybiswas/clippy/assets/92045934/c31d7fab-24a8-4728-bd07-6c3fac9209c3)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure go ahead

**Comment by kom-senapati** [comment]
@subinoybiswas I am participating in vsoc not gssoc
