### ISSUE TITLE
[Documentation Update]: Improper links

### ISSUE THREAD

**Issue by kom-senapati** [subinoybiswas/clippy#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Some links are not properly shown.

![image](https://github.com/subinoybiswas/clippy/assets/92045934/a2ab569d-265f-4edd-8837-d838e2038c7f)

### Suggested Change

They should be properly shown to all users.

### Rationale

To create a good readme.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Sure go ahead
