### ISSUE TITLE
Back button should be at the right only so user can back after clicking the link from the right side for ease

### ISSUE THREAD

**Issue by Utsavladia** [subinoybiswas/clippy#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When the user click right side button 
![image](https://github.com/subinoybiswas/clippy/assets/124615886/dc5c845b-d452-4a08-a07f-d6403dadde90)

Back option appears on left so if he dont want to read alll he have to go to all the way to the left to back 
it should be on the same size to have a smooth experience

![image](https://github.com/subinoybiswas/clippy/assets/124615886/53a0f0fd-f51f-4ac1-bf48-999153cf4dc2)

### Use Case

Smooth experience with ease

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
okay make assigning you
