### ISSUE TITLE
[Documentation Update]: Enhance Readme.md

### ISSUE THREAD

**Issue by ananyag309** [subinoybiswas/clippy#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I aim to enhance the README file for better organization and readability. Although these file are well-maintained, improvements can be made by adjusting spacing, font size, and alignment. I also want to add gssoc label to it and some more additions which will make it look more better. This is my first issue, admin @subinoybiswas  if needed please assign this issue to me under gssoc. 

### Suggested Change

1 - Addition of GSSOC Label:
Include a badge or label indicating participation in GSSOC.
Provide a brief description or link explaining what GSSOC is for newcomers.

2- Standardize font sizes and styles for headings and text to maintain a cohesive look. Also ensure code blocks are properly formatted with appropriate syntax highlighting.

etc

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by subinoybiswas** [comment]
Assigned
